<?php

use Illuminate\Database\Seeder;

class OrgDatelTableSeeder extends Seeder
{
    public function __construct(){
        date_default_timezone_set('Asia/Jakarta');
    }
    
    public function run()
    {
        DB::table('org_datels')->insert(['name' => 'NASIONAL','id_witel' => '1','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL ACEH','id_witel' => '2','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL LHOKSEUMAWE','id_witel' => '2','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MEULABOH','id_witel' => '2','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL LANGSA','id_witel' => '2','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PANGKAL PINANG','id_witel' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BELITUNG','id_witel' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BENGKULU','id_witel' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MUKO MUKO','id_witel' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL JAMBI','id_witel' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MUARA BUNGO','id_witel' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL LAMPUNG','id_witel' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL KOTABUMI','id_witel' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL METRO','id_witel' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MEDAN','id_witel' => '7','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BINJAI','id_witel' => '7','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL LUBUK PAKAM','id_witel' => '7','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PEKANBARU','id_witel' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL DUMAI','id_witel' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL INDRAGIRI','id_witel' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BATAM','id_witel' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL TANJUNG BALAI KARIMUN','id_witel' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL TANJUNG PINANG','id_witel' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PADANG','id_witel' => '10','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BUKITTINGGI','id_witel' => '10','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SOLOK','id_witel' => '10','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PALEMBANG','id_witel' => '11','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BATU RAJA','id_witel' => '11','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL LUBUK LINGGAU','id_witel' => '11','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PEMATANG SIANTAR','id_witel' => '12','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL KABANJAHE','id_witel' => '12','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL KISARAN','id_witel' => '12','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PADANG SIDEMPUAN','id_witel' => '12','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL RANTAUPRAPAT','id_witel' => '12','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SIBOLGA','id_witel' => '12','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SERANG','id_witel' => '13','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL CIKUPA','id_witel' => '13','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL CILEGON','id_witel' => '13','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL RANGKAS-PANDEGLANG','id_witel' => '13','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BEKASI','id_witel' => '14','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BOGOR','id_witel' => '15','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL CIBINONG','id_witel' => '15','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL DEPOK','id_witel' => '15','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL KUJANG','id_witel' => '15','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL JAKARTA BARAT','id_witel' => '16','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL JAKARTA PUSAT','id_witel' => '17','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL JAKARTA SELATAN','id_witel' => '18','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL JAKARTA TIMUR','id_witel' => '19','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL JAKARTA UTARA','id_witel' => '20','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL TANGERANG','id_witel' => '21','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL CIPUTAT','id_witel' => '21','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL LENGKONG','id_witel' => '21','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PASAR BARU','id_witel' => '21','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BANDUNG','id_witel' => '22','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SUMEDANG','id_witel' => '22','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL CIMAHI','id_witel' => '23','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PADALARANG','id_witel' => '23','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SOREANG','id_witel' => '23','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL CIREBON','id_witel' => '24','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL INDRAMAYU','id_witel' => '24','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL KUNINGAN','id_witel' => '24','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MAJALENGKA','id_witel' => '24','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL KARAWANG','id_witel' => '25','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PURWAKARTA','id_witel' => '25','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SUBANG','id_witel' => '25','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SUKABUMI','id_witel' => '26','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL CIANJUR','id_witel' => '26','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL CIBADAK','id_witel' => '26','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SINDANGLAYA','id_witel' => '26','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL TASIKMALAYA','id_witel' => '27','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BANJAR','id_witel' => '27','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL CIAMIS','id_witel' => '27','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL GARUT','id_witel' => '27','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SINGAPARNA','id_witel' => '27','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL YOGYAKARTA','id_witel' => '28','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BANTUL','id_witel' => '28','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SLEMAN','id_witel' => '28','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL KUDUS','id_witel' => '29','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BLORA','id_witel' => '29','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL JEPARA','id_witel' => '29','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PATI','id_witel' => '29','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PURWODADI','id_witel' => '29','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MAGELANG','id_witel' => '30','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL KEBUMEN','id_witel' => '30','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MUNTILAN','id_witel' => '30','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PURWOREJO','id_witel' => '30','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL TEMANGGUNG','id_witel' => '30','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL WONOSOBO','id_witel' => '30','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PEKALONGAN','id_witel' => '31','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BATANG','id_witel' => '31','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BREBES','id_witel' => '31','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PEMALANG','id_witel' => '31','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SLAWI','id_witel' => '31','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL TEGAL','id_witel' => '31','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PURWOKERTO','id_witel' => '32','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BANJARNEGARA','id_witel' => '32','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL CILACAP','id_witel' => '32','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PURBALINGGA','id_witel' => '32','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SEMARANG','id_witel' => '33','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL KENDAL','id_witel' => '33','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL UNGARAN','id_witel' => '33','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SOLO','id_witel' => '34','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL KLATEN','id_witel' => '34','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SALATIGA','id_witel' => '34','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SRAGEN','id_witel' => '34','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL WONOGIRI','id_witel' => '34','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL DENPASAR','id_witel' => '35','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL GRESIK','id_witel' => '36','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BANGKALAN','id_witel' => '36','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BOJONEGORO','id_witel' => '36','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL LAMONGAN','id_witel' => '36','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PAMEKASAN','id_witel' => '36','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SUMENEP','id_witel' => '36','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL TUBAN','id_witel' => '36','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL JEMBER','id_witel' => '37','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BANYUWANGI','id_witel' => '37','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SITUBONDO-BONDOWOSO','id_witel' => '37','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL TANGGUL','id_witel' => '37','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL KEDIRI','id_witel' => '38','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BLITAR','id_witel' => '38','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL NGANJUK','id_witel' => '38','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL TULUNG AGUNG','id_witel' => '38','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MADIUN','id_witel' => '39','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL NGAWI','id_witel' => '39','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PONOROGO','id_witel' => '39','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MALANG','id_witel' => '40','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BATU','id_witel' => '40','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL KEPANJEN','id_witel' => '40','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MATARAM','id_witel' => '41','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BIMA','id_witel' => '41','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SUMBAWA','id_witel' => '41','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL KUPANG','id_witel' => '42','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MAUMERE','id_witel' => '42','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SUMBA','id_witel' => '42','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PASURUAN','id_witel' => '43','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL LUMAJANG','id_witel' => '43','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PROBOLINGGO','id_witel' => '43','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SIDOARJO','id_witel' => '44','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL JOMBANG','id_witel' => '44','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MOJOKERTO','id_witel' => '44','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PANDAAN','id_witel' => '44','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SINGARAJA','id_witel' => '45','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL GIANYAR','id_witel' => '45','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL TABANAN','id_witel' => '45','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SURABAYA','id_witel' => '46','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BALIKPAPAN','id_witel' => '47','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL TANAHGROGOT','id_witel' => '47','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PONTIANAK','id_witel' => '48','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL KETAPANG','id_witel' => '48','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SANGGAU','id_witel' => '48','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SINGKAWANG','id_witel' => '48','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SINTANG','id_witel' => '48','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MEMPAWAH','id_witel' => '48','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BANJARMASIN','id_witel' => '49','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BANJARBARU','id_witel' => '49','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BATULICIN','id_witel' => '49','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL TANJUNG TABALONG','id_witel' => '49','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PALANGKARAYA','id_witel' => '50','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MUARATEWEH','id_witel' => '50','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PANGKALAN BUN','id_witel' => '50','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL TARAKAN','id_witel' => '51','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BULUNGAN BERAU','id_witel' => '51','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SAMARINDA','id_witel' => '52','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BONTANG','id_witel' => '52','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL GORONTALO','id_witel' => '53','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL AMBON','id_witel' => '54','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL TUAL','id_witel' => '54','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL JAYAPURA','id_witel' => '55','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL ABEPURA','id_witel' => '55','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MERAUKE','id_witel' => '55','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL TIMIKA','id_witel' => '55','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL SORONG','id_witel' => '56','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BIAK','id_witel' => '56','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL FAK FAK','id_witel' => '56','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MANOKWARI','id_witel' => '56','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MAKASSAR','id_witel' => '57','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BONE','id_witel' => '57','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL GOWA','id_witel' => '57','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PARE PARE','id_witel' => '58','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MAMUJU','id_witel' => '58','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PALOPO','id_witel' => '58','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL PALU','id_witel' => '59','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL LUWUK','id_witel' => '59','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL POSO','id_witel' => '59','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL KENDARI','id_witel' => '60','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BAU BAU','id_witel' => '60','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL MENADO','id_witel' => '61','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL BITUNG','id_witel' => '61','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL KOTAMOBAGO','id_witel' => '61','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
        DB::table('org_datels')->insert(['name' => 'DATEL TERNATE','id_witel' => '61','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s'),]);
    }
}
